# Generated by Django 3.0.5 on 2020-04-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bb', 'boubou'), ('rb', 'robe'), ('jp', 'jupe'), ('pt', 'pantalon'), ('mi', 'miel'), ('be', 'beurre')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
