# Generated by Django 3.0.5 on 2020-04-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200430_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='user_id',
        ),
    ]
