# Generated by Django 3.0.5 on 2020-05-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200503_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pourcentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
