# Generated by Django 3.0.5 on 2020-05-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_item_pourcentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='pourcentage',
            new_name='reduction',
        ),
    ]
