# Generated by Django 3.0.5 on 2020-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200503_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('bb', 'boubou'), ('rb', 'robe'), ('jp', 'jupe'), ('pt', 'pantalon'), ('mi', 'miel'), ('be', 'beurre'), ('ba', 'basin'), ('pagne baoule', 'pagne baoule')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='reduction',
            field=models.IntegerField(),
        ),
    ]
