# Generated by Django 3.0.5 on 2020-05-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
    ]
