# Generated by Django 3.0.5 on 2020-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='category',
            field=models.CharField(blank=True, choices=[('bb', 'boubou'), ('rb', 'robe'), ('jp', 'jupe'), ('pt', 'pantalon'), ('mi', 'miel'), ('be', 'beurre'), ('ba', 'basin'), ('pagne baoule', 'pagne baoule')], max_length=30, null=True),
        ),
    ]
