# Generated by Django 3.0.5 on 2020-05-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_over_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
