# Generated by Django 3.0.5 on 2020-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_slide_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='price',
        ),
        migrations.AddField(
            model_name='over_product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
